name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: ["Build Project"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'gh-pages' # Checkout the gh-pages branch

      - name: Download dist folder from artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: .

      - name: Deploy to gh-pages
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git rm -r --ignore-unmatch .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push
